services:
  database:
    image: mariadb:latest
    container_name: database_container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=microservices
    volumes:
      - mysqlvol:/var/lib/mysql
    networks:
      - microservicesIntro
    ports:
      - "3306:3306"


volumes:
  mysqlvol: {}
networks:
  microservicesIntro: {}