spring:
    application:
        name: Professor-Service
    datasource:
        url: jdbc:mariadb://localhost:3306/microservices
        username: root
        password: root
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
        database: mysql
server:
    port: 8083

